/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Users\xeyon\source\repos\VisualSim\out\build\x64-Debug\fgfdm_log/dds_gui.h
  Source: C:\Users\xeyon\source\repos\VisualSim\fgfdm_log\dds_gui.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#ifndef DDSC_C__USERS_XEYON_SOURCE_REPOS_VISUALSIM_OUT_BUILD_X64_DEBUG_FGFDM_LOG_DDS_GUI_H
#define DDSC_C__USERS_XEYON_SOURCE_REPOS_VISUALSIM_OUT_BUILD_X64_DEBUG_FGFDM_LOG_DDS_GUI_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define FG_DDS_GUI_VERSION 1
#define FG_DDS_TANKS 8
typedef struct FG_DDS_GUI
{
  int16_t id;
  int16_t version;
  double longitude;
  double latitude;
  float altitude;
  float agl;
  float phi;
  float theta;
  float psi;
  float vcas;
  float climb_rate;
  uint16_t num_tanks;
  float fuel_quantity[8];
  uint64_t cur_time;
  uint64_t warp;
  float ground_elev;
  float tuned_freq;
  float nav_radial;
  bool in_range;
  float dist_nm;
  float course_deviation_deg;
  float gs_deviation_deg;
} FG_DDS_GUI;

extern const dds_topic_descriptor_t FG_DDS_GUI_desc;

#define FG_DDS_GUI__alloc() \
((FG_DDS_GUI*) dds_alloc (sizeof (FG_DDS_GUI)));

#define FG_DDS_GUI_free(d,o) \
dds_sample_free ((d), &FG_DDS_GUI_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__USERS_XEYON_SOURCE_REPOS_VISUALSIM_OUT_BUILD_X64_DEBUG_FGFDM_LOG_DDS_GUI_H */
