/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: C:\Users\xeyon\source\repos\VisualSim\out\build\x64-Debug\fgfdm_log/dds_props.h
  Source: C:\Users\xeyon\source\repos\VisualSim\fgfdm_log\dds_props.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#ifndef DDSC_C__USERS_XEYON_SOURCE_REPOS_VISUALSIM_OUT_BUILD_X64_DEBUG_FGFDM_LOG_DDS_PROPS_H
#define DDSC_C__USERS_XEYON_SOURCE_REPOS_VISUALSIM_OUT_BUILD_X64_DEBUG_FGFDM_LOG_DDS_PROPS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#define FG_DDS_PROP_VERSION 0
#define FG_DDS_PROP_REQUEST -1
#define FG_DDS_MODE_READ false
#define FG_DDS_MODE_WRITE true
typedef enum FG_propType
{
  FG_DDS_NONE,
  FG_DDS_ALIAS,
  FG_DDS_BOOL,
  FG_DDS_INT,
  FG_DDS_LONG,
  FG_DDS_FLOAT,
  FG_DDS_DOUBLE,
  FG_DDS_STRING,
  FG_DDS_UNSPECIFIED
} FG_propType;

#define FG_propType__alloc() \
((FG_propType*) dds_alloc (sizeof (FG_propType)));

typedef struct FG_propValue
{
  FG_propType _d;
  union
  {
    bool Bool;
    int32_t Int32_i4;
    int64_t Int64_i8;
    float Float32_f4;
    double Float64_f8;
    char * String_c1;
  } _u;
} FG_propValue;

typedef struct FG_DDS_prop
{
  int32_t id;
  uint8_t version;
  bool mode;
  struct FG_propValue val;
  uint8_t guid[16];
} FG_DDS_prop;

extern const dds_topic_descriptor_t FG_DDS_prop_desc;

#define FG_DDS_prop__alloc() \
((FG_DDS_prop*) dds_alloc (sizeof (FG_DDS_prop)));

#define FG_DDS_prop_free(d,o) \
dds_sample_free ((d), &FG_DDS_prop_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_C__USERS_XEYON_SOURCE_REPOS_VISUALSIM_OUT_BUILD_X64_DEBUG_FGFDM_LOG_DDS_PROPS_H */
